name: CI

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Setup Node v18
        uses: actions/setup-node@v3
        with:
          registry-url: 'https://npm.pkg.github.com'
          node-version: 18

      - name: Install dependencies
        run: |
          cat <<EOF > .npmrc
          registry=https://registry.npmjs.org/
          @aet-services:registry=https://npm.pkg.github.com/
          //npm.pkg.github.com/:_authToken=${{secrets.NPM_PKG_GITHUB_AUTH_TOKEN}}
          EOF
          npm i

      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
